apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME-node-0-production-testing
  namespace: chain-prd-testing
spec:
  ports:
  - name: ws
    port: 9900
    targetPort: 9900
    protocol: TCP
  - name: https
    port: 9934
    targetPort: 9934
    protocol: TCP
  - name: tcp
    port: 30333
    targetPort: 30333
    protocol: TCP
  selector:
    app: $APP_NAME-node-0-production-testing
  sessionAffinity: None
#  type: NodePort
  type: ClusterIP
